---
title: "Кто покупает в чёрную пятницу?"
author: "Sergey Sidorov"
date: "27/11/2018"
output: 
  html_document:
    toc: yes
    toc_float: yes
    keep_md: true
urlcolor: blue
---
 


<div style= "float:right;position: relative; top: -20px;">
<img src="IMG/1.png" width="350px" />
</div>

## Введение
Как же достала эта чёрная пятница! 

Проскакивала эта мысль в голове за последнюю неделю? Каждый год одно и то же: тебя забрасывают рекламными сообщениями и говорят, что тебе невероятно повезло и ты можешь крупно сэкономить.

Что ж, возможно, кому-то это удавалось. Я же понял, что это очень хорошая возможность заработать для магазинов, и небольшая возможность купить что-то классное по действительно выгодной цене. 

Тоже так думаете? Считаете, что никто не покупает в этот период? Как бы не так. И сегодня вы в этом убедитесь!

## Что исследуем?


[Сегодняшний датасет](https://www.kaggle.com/mehdidag/black-friday) почти в 50 раз больше, чем в [первом исследовании](http://rpubs.com/sergeymong/441686)! В нём **537 577** наблюдений. 

Это [база данных](https://www.kaggle.com/mehdidag/black-friday) одного из ритейлеров, в котором содержатся наблюдения покупок в период чёрной пятницы.

Посмотрим, какие наблюдения он содержит:

- User_ID -- уникальный код клиента;
- Product_ID -- уникальный код товара;
- Gender -- пол клиента;
- Age -- возрастная категория клиента;
- Occupation -- профессия;
- City_Category -- классификация города по размерности или достатку;
- Stay_In_Current_City_Years -- сколько лет человек живёт в городе;
- Marital_Status -- статус семейного положения;
- Product_Category_1 -- категория продукта;
- Purchase -- сумма покупки ($).

В описании данных не было расшифровки категорий продукта и профессий, а также точных критериев для размерности города. Также неизвестны страна и название ритейлера и за какой временной период собирались данные.

Мне удалось найти описание [классификации городов](https://www.finmin.nic.in/sites/default/files/27-11-1965_0.pdf) по схожей схеме, и она учитывает размер заработных плат в этом городе. Будем считать, что город класса A выше по оплате труда, чем С.

Итого мы имеем:

```
## Observations: 537,577
## Variables: 12
## $ User_ID                    <int> 1000001, 1000001, 1000001, 1000001,...
## $ Product_ID                 <chr> "P00069042", "P00248942", "P0008784...
## $ Gender                     <chr> "F", "F", "F", "F", "M", "M", "M", ...
## $ Age                        <chr> "0-17", "0-17", "0-17", "0-17", "55...
## $ Occupation                 <int> 10, 10, 10, 10, 16, 15, 7, 7, 7, 20...
## $ City_Category              <chr> "A", "A", "A", "A", "C", "A", "B", ...
## $ Stay_In_Current_City_Years <chr> "2", "2", "2", "2", "4+", "3", "2",...
## $ Marital_Status             <int> 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,...
## $ Product_Category_1         <int> 3, 1, 12, 12, 8, 1, 1, 1, 1, 8, 5, ...
## $ Product_Category_2         <int> NA, 6, NA, 14, NA, 2, 8, 15, 16, NA...
## $ Product_Category_3         <int> NA, 14, NA, NA, NA, NA, 17, NA, NA,...
## $ Purchase                   <int> 8370, 15200, 1422, 1057, 7969, 1522...
```

## Вопросы и гипотезы
Какие у вас возникли вопросы при просмотре структуры датасета? У меня сразу же возникли следующие:

1. [Кто покупает больше товаров?](#purchsex)
2. [Кто тратит больше денег?](#moneysex)
3. [У кого выше средний чек?](#averagechsex) [^1]
4. [Как брак влияет на покупки?](#mariagepurch)
5. [Как город влияет на покупки?](#citypurch)
6. [Как тип города влияет на покупки человека?](#moneysex)
7. [Как количество лет в одном городе влияет на покупки?](#yearscitypurch)
8. [**Какая самая привлекательная аудитория в чёрную пятницу?**](#audience)

Их и будем проверять. Кстати, если вы хотели бы участвовать в формировании вопросов для анализа, **напишите в комментарии или личные сообщения**! 

Формат будет такой: я публикую описание датасета, вы пишете вопросы, на которые хотели бы узнать ответы. Потом я ищу ответы на ваши вопросы в датасете.

[^1]: [Что такое средний чек?](http://www.marketch.ru/marketing_dictionary/marketing_terms_s/sredniy_chek/) 

## Предобработка

Если вам не интересно, как сначала обрабатываются данные, можете смело переходить к [блоку анализа](#analysis).

***

Работа с датасетом происходит в R version 3.5.1 (2018-07-02).

### Обработка первичных данных
Проверяем на наличие пропусков в записях, чтобы понимать, на каких данных столбцах могут некорректно отрабатывать функции:

```
##                            col_num na_nums
## User_ID                          1       0
## Product_ID                       2       0
## Gender                           3       0
## Age                              4       0
## Occupation                       5       0
## City_Category                    6       0
## Stay_In_Current_City_Years       7       0
## Marital_Status                   8       0
## Product_Category_1               9       0
## Product_Category_2              10  166986
## Product_Category_3              11  373299
## Purchase                        12       0
```
Можно сказать, что нам крупно повезло -- основная часть данных не содержит пропусков, а та, что содержит, в контексте данного анализа неважна для нас. Поэтому удалим колонки Product_Category_2, Product_Category_3.

Дальше проверим, какие данные лучше превратить в [факторы](https://ru.wikibooks.org/wiki/%D0%AF%D0%B7%D1%8B%D0%BA_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_R/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5#Factors) -- это позволит быстрее группировать данные в дальнейшем:

```
##                            col_num  freq
## User_ID                          1  5891
## Product_ID                       2  3623
## Gender                           3     2
## Age                              4     7
## Occupation                       5    21
## City_Category                    6     3
## Stay_In_Current_City_Years       7     5
## Marital_Status                   8     2
## Product_Category_1               9    18
## Product_Category_2              10    18
## Product_Category_3              11    16
## Purchase                        12 17959
```

Все колонки со значением freq меньше 25 преобразуем в [фактор](https://ru.wikibooks.org/wiki/%D0%AF%D0%B7%D1%8B%D0%BA_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_R/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5#Factors).

После первичных преобразований получаем следующий датасет:

```
## Observations: 537,577
## Variables: 10
## $ User_ID                    <int> 1000001, 1000001, 1000001, 1000001,...
## $ Product_ID                 <chr> "P00069042", "P00248942", "P0008784...
## $ Gender                     <fct> Female, Female, Female, Female, Mal...
## $ Age                        <fct> 0-17, 0-17, 0-17, 0-17, 55+, 26-35,...
## $ Occupation                 <fct> 10, 10, 10, 10, 16, 15, 7, 7, 7, 20...
## $ City_Category              <fct> A, A, A, A, C, A, B, B, B, A, A, A,...
## $ Stay_In_Current_City_Years <fct> 2, 2, 2, 2, 4+, 3, 2, 2, 2, 1, 1, 1...
## $ Marital_Status             <fct> Not Married, Not Married, Not Marri...
## $ Product_Category_1         <fct> 3, 1, 12, 12, 8, 1, 1, 1, 1, 8, 5, ...
## $ Purchase                   <int> 8370, 15200, 1422, 1057, 7969, 1522...
```

### Формирование выборок для анализа

#### Выборка по пользователям
Чтобы ответить на первые три вопроса, нам понадобится выборка, сгруппированная по каждому пользователю. Всего в данных 537577 строк, а уникальных пользователей 5891 -- это говорит о том, что в наборе данных на каждого пользователя по несколько покупок. Формируем сабсет:

```
## Observations: 5,891
## Variables: 9
## $ User_ID                    <int> 1004277, 1001680, 1002909, 1001941,...
## $ Gender                     <fct> Male, Male, Male, Male, Male, Male,...
## $ Age                        <fct> 36-45, 26-35, 26-35, 36-45, 26-35, ...
## $ Marital_Status             <fct> Not Married, Married, Not Married, ...
## $ Stay_In_Current_City_Years <fct> 0, 3, 1, 1, 3, 0, 4+, 0, 3, 3, 1, 1...
## $ City_Category              <fct> A, A, A, A, A, A, A, A, A, A, A, A,...
## $ purchases                  <int> 978, 1025, 717, 898, 694, 574, 739,...
## $ sum_p_thous                <S3: formattable> $10,536.78, $8,699.23, ...
## $ avg_purch_thous            <S3: formattable> $10.77, $8.49, $10.57, ...
```

Для удобства анализа все денежные данные приведены к формату валюты. Также для удобства восприятия сумма покупок представляется в тысячах. 

![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-8-1.png)<!-- -->

На графике видим, что три последних значения сильно отклоняются от выборки -- это выборсы. Так как они могут искажать выводы и результаты тестов, удаляем.

#### Выборка по статусу брака
Данная выборка позволит понять абсолютную разницу между поведением покупателей в зависимости от семейного положения по целевым показателям:

```
## Observations: 12
## Variables: 5
## $ Age        <fct> 18-25, 18-25, 26-35, 26-35, 36-45, 36-45, 46-50, 46...
## $ Gender     <fct> Female, Male, Female, Male, Female, Male, Female, M...
## $ diff_p     <dbl> -5, 14, 3, 0, 4, -3, -11, -6, 5, 0, 12, -2
## $ diff_avg_p <S3: formattable> $0.36, $-0.31, $-0.33, $0.12, $0.20, $0...
## $ diff_sum_p <S3: formattable> $7.84, $128.90, $-2.10, $10.79, $42.87,...
```

#### Выборка по типу городов
Благодаря этому датасету мы получим ответы на вопросы, связанные с типами городов:

```
## Observations: 376
## Variables: 10
## $ City_Category              <fct> B, B, C, A, B, B, B, B, C, A, A, A,...
## $ Gender                     <fct> Male, Male, Male, Male, Male, Male,...
## $ Age                        <fct> 26-35, 26-35, 26-35, 26-35, 26-35, ...
## $ Marital_Status             <fct> Not Married, Married, Not Married, ...
## $ Stay_In_Current_City_Years <fct> 1, 1, 1, 1, 3, 2, 1, 1, 1, 2, 3, 4+...
## $ users                      <int> 98, 71, 136, 69, 48, 59, 63, 57, 10...
## $ purchases                  <int> 14619, 9748, 8576, 9114, 8714, 8460...
## $ sum_p_thous                <S3: formattable> $138,838.71, $92,520.21...
## $ avg_purch_thous            <S3: formattable> $1,416.72, $1,303.10, $...
## $ avg_purch_per_order        <S3: formattable> $9.50, $9.49, $10.02, $...
```

На этом обработка и предобработка данных завершена.

## Анализ {#analysis}

### Кто покупает больше товаров? {#purchsex}
Для начала посмотрим, кто делает больше покупок? 
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-11-1.png)<!-- -->

На (Рис. 1) видим, что женщины совершают меньше покупок. В среднем женщины покупают **79** товаров, а мужчины **95**.

Сделаем чуть более наглядный график:
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-12-1.png)<!-- -->
<font size = "1">*Тест Стьюдента показывает, что различия значимые, так как p-value -- 0.014. [Подробнее о тесте](https://ru.wikipedia.org/wiki/T-%D0%9A%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B9_%D0%A1%D1%82%D1%8C%D1%8E%D0%B4%D0%B5%D0%BD%D1%82%D0%B0). *</font>

Те, кто не в браке -- покупают больше (Рис. 2). Возможно, это связано с тем, что в браке добавляются такие статьи расходов, как ребёнок, ипотека и прочее.

### Кто тратит больше денег? {#moneysex}
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-13-1.png)<!-- -->

Мужчины больше тратят, чем женщины, причём существенно -- на **30%** (Рис. 3). Женщины в среднем тратят $699.05, а мужчны $906.26 тысяч долларов.

![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-14-1.png)<!-- -->
<font size = "1">*Тест Стьюдента показывает, что различия значимые, так как p-value -- 0.014. [Подробнее о тесте](https://ru.wikipedia.org/wiki/T-%D0%9A%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B9_%D0%A1%D1%82%D1%8C%D1%8E%D0%B4%D0%B5%D0%BD%D1%82%D0%B0). *</font>

На (Рис. 4) видим, что люди не в браке тратят больше. Возможно, это связано с тем, что количество покупок у них тоже больше. Давайте выявим [корреляцию](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%80%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D1%8F#%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D1%8D%D1%84%D1%84%D0%B8%D1%86%D0%B8%D0%B5%D0%BD%D1%82_%D0%BA%D0%BE%D1%80%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D0%B8). Её коэффициент составляет: 0.9787397. Это говорит практически об абсолютной взаимосвязи (максимальное значение коэффициента -- 1).

### У кого выше средний чек? {#averagechsex}
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-15-1.png)<!-- -->
<font size = "1">*Тест Стьюдента показывает, что различия значимые, так как p-value -- 0.028. [Подробнее о тесте](https://ru.wikipedia.org/wiki/T-%D0%9A%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B9_%D0%A1%D1%82%D1%8C%D1%8E%D0%B4%D0%B5%D0%BD%D1%82%D0%B0). *</font>

По среднему чеку видим (Рис. 5), что мужчины на каждую покупку тратят на **9%** больше женщин.

![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-16-1.png)<!-- -->

Замужние женщины начинают тратить больше, а женатые мужчины незначительно меньше (Рис. 6). Возможно, это связано с тем, что в некоторых семьях присутствуют общие бюджеты, из которых женщина делает дополнительные покупки для быта, семьи или себя.

### Как брак влияет на покупки? {#mariagepurch}
Давайте чуть глубже взглянем на разницу в совершении покупок для людей, которые вошли в брак и тех, кто ещё нет. 

Для этого сделали отдельный датасет. Так как выше мы обнаружили, что люди не в браке тратят больше, то все следующие графики, будут представлены, как **разница между внебрачными и брачными людьми**.

#### Количество покупок
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-17-1.png)<!-- -->
Отрицательные значения на графике говорят о том, что **до брака люди тратят меньше, чем в браке**.

Здесь видим очень большую разницу для мужчин категории 18-25 лет (Рис. 7). Возможно, это связано с тем, что молодые мужчины вне брака тратят всё на своё развитие, развлечения и получение опыта. Мужчины же в браке могут быть обременены ипотекой, кредитами или расходами на ребёнка и жену. 

Касательно остальных возрастных категорий пусть каждый сделает свои предположения и **напишет их в комментариях**, мы вместе обсудим и определим наиболее интересную догадку.

#### Сумма покупок
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-18-1.png)<!-- -->

Главные отклонения наблюдаются по тем же категориям, что количество покупок (Рис. 7).

При этом видим (Рис. 8), что практически все люди, кроме категории 46-50, вне брака тратят больше, чем в браке. 

С чем это может быть связано? Больше денег уходит на быт и ребёнка? Ответить сложно, так как мы не знаем конкретной страны и год, в которые собиралась данная статистика. Если бы у нас была данная информация, то мы согли бы её собрать и дополнить картину.

#### Средний чек
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-19-1.png)<!-- -->

По среднему чеку видим любопытные отклонения (Рис. 9). Помним, что мужчины категории 18-25 делают больше покупок (Рис. 7), но при этом это менее дорогие покупки, чем у женщин. 

Можно сделать предположение, что они тратят больше денег на безделушки или ещё не задумываются о качестве покупаемого товара, выбирая более дешёвые вещи.

### Как город влияет на покупки? {#citypurch}
Напомню, что в датасете города разбиты на три категории -- A, B, C. Удалось найти похожую [классификацию городов](https://www.finmin.nic.in/sites/default/files/27-11-1965_0.pdf). Поэтому будем придерживаться позиции, что город класса A наполняют люди с большим доходом, чем в городе класса C. Соответственно, доходы жителей: A > B > C.

Предварительно поймём, сколько людей живёт в каждом типе городов:
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-20-1.png)<!-- -->

Количество людей распределяется в зависимости от достатка -- чем выше достаток, тем меньше людей (Рис. 10).

#### Количество покупок
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-21-1.png)<!-- -->

Видим, что в чёрную пятницу гораздо больше покупок совершают жители городов категории B (Рис. 11). Они делают на **60%** больше покупок, чем жители городов типа A, и на **36%** больше покупок, чем жители городов типа C. 

В свою очередь жители городов типа C делают на **17%** больше покупок, чем жители городов типа A.

#### Сумма покупок
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-22-1.png)<!-- -->

Наблюдаем, что корреляция между количеством покупок и суммой продолжает сохраняться. Жители городов категории B делают на **64%** больше покупок, чем жители городов типа A, и на **27%** больше покупок, чем жители городов типа C (Рис. 12). 

В свою очередь жители городов типа C делают на **29%** больше покупок, чем жители городов типа A.

#### Средний чек покупок
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-23-1.png)<!-- -->

Cредний чек больше всего у жителей городов типа A и видим взаимосвязь -- чем выше класс города, тем больше средний чек.

Средний чек значительно меньше в городах категории C: на **130%**, чем у жителей городов типа A, и на **127%**, чем у жителей городов типа B (Рис. 13).

### Как количество лет в городе, влияет на покупки? {#yearscitypurch}
***
<font size = "7">Никак.</font>

***

Почти. 

Если вам интересно посмотреть на графики, показывающие это -- листайте дальше. Если нет -- [переключайтесь к определению портрета самой платёжеспособной аудитории](#audiece).

#### Как долго люди находятся в городах?
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-24-1.png)<!-- -->

Видим, что наибольшее количество людей проживает в каждом типе городов около 1 года, а распределение по количеству лет одинаковое для каждого класса городов (Рис. 14).

Это может говорить о большом количестве приезжих людей. Всего людей, проживающих в городе дольше 4-х лет **только 15.4%**.

#### Количество покупок
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-25-1.png)<!-- -->
<font size = "1">*Тест Стьюдента показывает, что различия значимые, так как p-value -- 0. [Подробнее о тесте](https://ru.wikipedia.org/wiki/T-%D0%9A%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B9_%D0%A1%D1%82%D1%8C%D1%8E%D0%B4%D0%B5%D0%BD%D1%82%D0%B0). *</font>

#### Сумма покупок
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-26-1.png)<!-- -->
<font size = "1">*Тест Стьюдента показывает, что всё же различия значимые, так как p-value -- 0. [Подробнее о тесте](https://ru.wikipedia.org/wiki/T-%D0%9A%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B9_%D0%A1%D1%82%D1%8C%D1%8E%D0%B4%D0%B5%D0%BD%D1%82%D0%B0). *</font>

#### Средний чек
![](BlackFridayAnalysis_files/figure-html/unnamed-chunk-27-1.png)<!-- -->
<font size = "1">*Тест Стьюдента показывает, что всё же различия значимые, так как p-value -- 0. [Подробнее о тесте](https://ru.wikipedia.org/wiki/T-%D0%9A%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B9_%D0%A1%D1%82%D1%8C%D1%8E%D0%B4%D0%B5%D0%BD%D1%82%D0%B0). *</font>

### Самая привлекательная аудитория в чёрную пятницу {#audience}
Итак, мы подошли к самому главному -- на кого стоило бы таргетировать свою рекламу с точки зрения полученных денег? **Графики ниже интерактивные**. Вы можете выбрать нужную возрастную категорию:
<!--html_preserve--><div id="htmlwidget-e3291959332daa826833" style="width:950px;height:700px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-e3291959332daa826833">{"x":{"data":[{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[1,1,1,1],"y":[6225.804,2611.457,1439.93,985.014],"text":["Age: 0-17<br />sum_p_thous: $6,225.80<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $2,611.46<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $1,439.93<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $985.01<br />Age: 0-17"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"0-17","legendgroup":"0-17","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[1,1,1,1],"y":[3349.378,3271.59,2250.784,1523.262],"text":["Age: 0-17<br />sum_p_thous: $3,349.38<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $3,271.59<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $2,250.78<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $1,523.26<br />Age: 0-17"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"0-17","legendgroup":"0-17","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[1,1,1,1,1],"y":[4933.591,4764.656,2132.705,1354.219,545.641],"text":["Age: 0-17<br />sum_p_thous: $4,933.59<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $4,764.66<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $2,132.70<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $1,354.22<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $545.64<br />Age: 0-17"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"0-17","legendgroup":"0-17","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[1,1,1,1,1],"y":[13525.376,10080.759,4894.266,3353.859,1928.71],"text":["Age: 0-17<br />sum_p_thous: $13,525.38<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $10,080.76<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $4,894.27<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $3,353.86<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $1,928.71<br />Age: 0-17"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"0-17","legendgroup":"0-17","showlegend":false,"xaxis":"x3","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[1,1,1,1,1],"y":[5575.093,4647.282,2647.312,2390.729,1573.182],"text":["Age: 0-17<br />sum_p_thous: $5,575.09<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $4,647.28<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $2,647.31<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $2,390.73<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $1,573.18<br />Age: 0-17"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"0-17","legendgroup":"0-17","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[1,1,1,1,1],"y":[14263.734,10718.749,8805.215,6584.41,6282.299],"text":["Age: 0-17<br />sum_p_thous: $14,263.73<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $10,718.75<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $8,805.22<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $6,584.41<br />Age: 0-17","Age: 0-17<br />sum_p_thous: $6,282.30<br />Age: 0-17"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"0-17","legendgroup":"0-17","showlegend":false,"xaxis":"x3","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[17711.75,10072.756,5445.677,3846.973,2836.076],"text":["Age: 18-25<br />sum_p_thous: $17,711.75<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $10,072.76<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $5,445.68<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $3,846.97<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $2,836.08<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[3528.877,2523.649,2454.735,1612.542,182.644],"text":["Age: 18-25<br />sum_p_thous: $3,528.88<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $2,523.65<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $2,454.74<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $1,612.54<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $182.64<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[48307.058,32182.139,26413.1,22931.169,22620.918],"text":["Age: 18-25<br />sum_p_thous: $48,307.06<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $32,182.14<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $26,413.10<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $22,931.17<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $22,620.92<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[22251.597,5882.231,3591.454,3112.313,2662.33],"text":["Age: 18-25<br />sum_p_thous: $22,251.60<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $5,882.23<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $3,591.45<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $3,112.31<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $2,662.33<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x4","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[19394.593,14477.439,13896.341,10477.47,9789.005],"text":["Age: 18-25<br />sum_p_thous: $19,394.59<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $14,477.44<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $13,896.34<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $10,477.47<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $9,789.01<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[10026.339,5851.631,5844.352,2486.493,171.549],"text":["Age: 18-25<br />sum_p_thous: $10,026.34<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $5,851.63<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $5,844.35<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $2,486.49<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $171.55<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[75144.827,48556.078,43852.154,35318.99,30068.456],"text":["Age: 18-25<br />sum_p_thous: $75,144.83<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $48,556.08<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $43,852.15<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $35,318.99<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $30,068.46<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x3","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[18670.113,15242.598,10090.488,9320.267,6503.848],"text":["Age: 18-25<br />sum_p_thous: $18,670.11<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $15,242.60<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $10,090.49<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $9,320.27<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $6,503.85<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x4","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[18540.161,8853.599,7696.82,6776.78,3489.738],"text":["Age: 18-25<br />sum_p_thous: $18,540.16<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $8,853.60<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $7,696.82<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $6,776.78<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $3,489.74<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[6245.182,3053.156,2393.124,1806.772,723.227],"text":["Age: 18-25<br />sum_p_thous: $6,245.18<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $3,053.16<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $2,393.12<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $1,806.77<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $723.23<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x2","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[52425.133,33939.153,33858.714,29594.637,26051.108],"text":["Age: 18-25<br />sum_p_thous: $52,425.13<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $33,939.15<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $33,858.71<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $29,594.64<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $26,051.11<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x3","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[2,2,2,2,2],"y":[13490.375,10342.831,7959.361,5217.452,3858.938],"text":["Age: 18-25<br />sum_p_thous: $13,490.38<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $10,342.83<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $7,959.36<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $5,217.45<br />Age: 18-25","Age: 18-25<br />sum_p_thous: $3,858.94<br />Age: 18-25"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"18-25","legendgroup":"18-25","showlegend":false,"xaxis":"x4","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[34673.491,17194.184,13282.492,9797.963,8808.164],"text":["Age: 26-35<br />sum_p_thous: $34,673.49<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $17,194.18<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $13,282.49<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $9,797.96<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $8,808.16<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[27882.699,13171.285,10720.121,10099.606,2893.378],"text":["Age: 26-35<br />sum_p_thous: $27,882.70<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $13,171.28<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $10,720.12<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $10,099.61<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $2,893.38<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[83468.072,64595.984,61342.705,58009.212,50263.482],"text":["Age: 26-35<br />sum_p_thous: $83,468.07<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $64,595.98<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $61,342.71<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $58,009.21<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $50,263.48<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[52435.048,40319.564,38201.459,17404.29,16888.736],"text":["Age: 26-35<br />sum_p_thous: $52,435.05<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $40,319.56<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $38,201.46<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $17,404.29<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $16,888.74<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x4","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[44660.105,29554.023,24167.582,12192.535,6904.492],"text":["Age: 26-35<br />sum_p_thous: $44,660.10<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $29,554.02<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $24,167.58<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $12,192.53<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $6,904.49<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[27717.006,12229.127,11829.312,6023.386,4816.133],"text":["Age: 26-35<br />sum_p_thous: $27,717.01<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $12,229.13<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $11,829.31<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $6,023.39<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $4,816.13<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[138838.708,81878.853,78640.002,52892.017,40300.773],"text":["Age: 26-35<br />sum_p_thous: $138,838.71<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $81,878.85<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $78,640.00<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $52,892.02<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $40,300.77<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x3","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[92520.215,49247.965,44240.348,38344.798,28782.57],"text":["Age: 26-35<br />sum_p_thous: $92,520.21<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $49,247.97<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $44,240.35<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $38,344.80<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $28,782.57<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x4","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[18345.715,12222.04,8406.752,8076.353,6178.757],"text":["Age: 26-35<br />sum_p_thous: $18,345.72<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $12,222.04<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $8,406.75<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $8,076.35<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $6,178.76<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[24282.664,12355.606,6258.725,5170.36,3943.624],"text":["Age: 26-35<br />sum_p_thous: $24,282.66<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $12,355.61<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $6,258.73<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $5,170.36<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $3,943.62<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x2","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[85952.06,46539.507,39773.507,38731.077,32359.364],"text":["Age: 26-35<br />sum_p_thous: $85,952.06<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $46,539.51<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $39,773.51<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $38,731.08<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $32,359.36<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x3","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[3,3,3,3,3],"y":[70363.983,37823.516,27812.929,26050.536,15593.409],"text":["Age: 26-35<br />sum_p_thous: $70,363.98<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $37,823.52<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $27,812.93<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $26,050.54<br />Age: 26-35","Age: 26-35<br />sum_p_thous: $15,593.41<br />Age: 26-35"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"26-35","legendgroup":"26-35","showlegend":false,"xaxis":"x4","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[11097.552,8089.589,7854.096,7608.705,6292.1],"text":["Age: 36-45<br />sum_p_thous: $11,097.55<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $8,089.59<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $7,854.10<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $7,608.70<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $6,292.10<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[5286.247,5035.185,4422.061,3048.547,2409.804],"text":["Age: 36-45<br />sum_p_thous: $5,286.25<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $5,035.19<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $4,422.06<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $3,048.55<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $2,409.80<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[37541.755,27222.275,10476.685,4550.38,2986.57],"text":["Age: 36-45<br />sum_p_thous: $37,541.75<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $27,222.27<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $10,476.68<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $4,550.38<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $2,986.57<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[26807.59,22522.177,14398.141,14235.687,3944.666],"text":["Age: 36-45<br />sum_p_thous: $26,807.59<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $22,522.18<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $14,398.14<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $14,235.69<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $3,944.67<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x4","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[31973.012,8864.11,7715.684,6497.408,2479.134],"text":["Age: 36-45<br />sum_p_thous: $31,973.01<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $8,864.11<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $7,715.68<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $6,497.41<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $2,479.13<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[16453.362,6807.003,5447.563,4772.416,4337.825],"text":["Age: 36-45<br />sum_p_thous: $16,453.36<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $6,807.00<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $5,447.56<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $4,772.42<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $4,337.82<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[74704.819,51932.204,33230.664,28782.923,26114.249],"text":["Age: 36-45<br />sum_p_thous: $74,704.82<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $51,932.20<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $33,230.66<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $28,782.92<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $26,114.25<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x3","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[35900.938,29348.536,28753.503,16200.291,6135.12],"text":["Age: 36-45<br />sum_p_thous: $35,900.94<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $29,348.54<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $28,753.50<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $16,200.29<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $6,135.12<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x4","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[20078.144,10761.91,9335.566,5985.845,3759.509],"text":["Age: 36-45<br />sum_p_thous: $20,078.14<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $10,761.91<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $9,335.57<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $5,985.85<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $3,759.51<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[9304.195,7649.846,6294.96,5379.59,3969.512],"text":["Age: 36-45<br />sum_p_thous: $9,304.19<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $7,649.85<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $6,294.96<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $5,379.59<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $3,969.51<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x2","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[47588.989,35114.299,30785.005,27306.262,18229.248],"text":["Age: 36-45<br />sum_p_thous: $47,588.99<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $35,114.30<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $30,785.01<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $27,306.26<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $18,229.25<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x3","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[4,4,4,4,4],"y":[28592.796,27443.535,19771.86,17022.567,13458.568],"text":["Age: 36-45<br />sum_p_thous: $28,592.80<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $27,443.53<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $19,771.86<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $17,022.57<br />Age: 36-45","Age: 36-45<br />sum_p_thous: $13,458.57<br />Age: 36-45"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"36-45","legendgroup":"36-45","showlegend":false,"xaxis":"x4","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9],"base":[0,0,0],"x":[5,5,5],"y":[1718.595,291.575,248.55],"text":["Age: 46-50<br />sum_p_thous: $1,718.60<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $291.58<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $248.55<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[5793.386,1679.715,485.094,333.466,127.747],"text":["Age: 46-50<br />sum_p_thous: $5,793.39<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $1,679.71<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $485.09<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $333.47<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $127.75<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[5,5,5,5],"y":[7881.199,5499.812,1976.89,1387.035],"text":["Age: 46-50<br />sum_p_thous: $7,881.20<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $5,499.81<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $1,976.89<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $1,387.04<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[13270.471,7852.617,6887.326,3823.103,3364.854],"text":["Age: 46-50<br />sum_p_thous: $13,270.47<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $7,852.62<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $6,887.33<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $3,823.10<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $3,364.85<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x4","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[3840.238,3416.144,2959.305,1500.671,317.337],"text":["Age: 46-50<br />sum_p_thous: $3,840.24<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $3,416.14<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $2,959.31<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $1,500.67<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $317.34<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[18893.732,11996.109,6249.642,3638.28,1661.067],"text":["Age: 46-50<br />sum_p_thous: $18,893.73<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $11,996.11<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $6,249.64<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $3,638.28<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $1,661.07<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[9012.613,7916.95,6255.089,3441.145,3252.528],"text":["Age: 46-50<br />sum_p_thous: $9,012.61<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $7,916.95<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $6,255.09<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $3,441.14<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $3,252.53<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x3","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[42078.519,24639.042,16189.239,9367.775,8386.659],"text":["Age: 46-50<br />sum_p_thous: $42,078.52<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $24,639.04<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $16,189.24<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $9,367.77<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $8,386.66<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x4","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[7897.798,1984.491,1663.197,808.756,466.652],"text":["Age: 46-50<br />sum_p_thous: $7,897.80<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $1,984.49<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $1,663.20<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $808.76<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $466.65<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[15548.877,7307.274,6590.667,4474.406,2904.222],"text":["Age: 46-50<br />sum_p_thous: $15,548.88<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $7,307.27<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $6,590.67<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $4,474.41<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $2,904.22<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x2","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[13145.075,8280.234,6630.233,5668.995,3960.43],"text":["Age: 46-50<br />sum_p_thous: $13,145.08<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $8,280.23<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $6,630.23<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $5,668.99<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $3,960.43<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x3","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[5,5,5,5,5],"y":[25719.431,18467.83,13841.66,12981.984,7442.492],"text":["Age: 46-50<br />sum_p_thous: $25,719.43<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $18,467.83<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $13,841.66<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $12,981.98<br />Age: 46-50","Age: 46-50<br />sum_p_thous: $7,442.49<br />Age: 46-50"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"46-50","legendgroup":"46-50","showlegend":false,"xaxis":"x4","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[6,6,6,6],"y":[1518.861,1073.281,647.526,574.549],"text":["Age: 51-55<br />sum_p_thous: $1,518.86<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,073.28<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $647.53<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $574.55<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[6,6,6,6],"y":[4862.128,3937.419,1999.27,673.267],"text":["Age: 51-55<br />sum_p_thous: $4,862.13<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $3,937.42<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,999.27<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $673.27<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[4272.476,4028.908,2462.344,1454.452,808.016],"text":["Age: 51-55<br />sum_p_thous: $4,272.48<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $4,028.91<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $2,462.34<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,454.45<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $808.02<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[17463.896,4341.114,3900.474,2113.852,1024.052],"text":["Age: 51-55<br />sum_p_thous: $17,463.90<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $4,341.11<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $3,900.47<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $2,113.85<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,024.05<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x4","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[6,6,6,6],"y":[8134.84,5479.529,1852.501,1146.998],"text":["Age: 51-55<br />sum_p_thous: $8,134.84<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $5,479.53<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,852.50<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,147.00<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[11364.472,3292.557,2963.225,2311.752,785.166],"text":["Age: 51-55<br />sum_p_thous: $11,364.47<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $3,292.56<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $2,963.22<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $2,311.75<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $785.17<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[10288.838,8529.048,4762.446,3238.596,561.825],"text":["Age: 51-55<br />sum_p_thous: $10,288.84<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $8,529.05<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $4,762.45<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $3,238.60<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $561.83<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x3","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[41884.431,17469.6,17283.964,13559.168,8874.941],"text":["Age: 51-55<br />sum_p_thous: $41,884.43<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $17,469.60<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $17,283.96<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $13,559.17<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $8,874.94<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x4","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[3627.587,3120.735,1964.982,1901.841,1152.17],"text":["Age: 51-55<br />sum_p_thous: $3,627.59<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $3,120.74<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,964.98<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,901.84<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,152.17<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[11969.748,4752.907,3525.869,1957.216,1382.011],"text":["Age: 51-55<br />sum_p_thous: $11,969.75<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $4,752.91<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $3,525.87<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,957.22<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $1,382.01<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x2","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[11669.244,5671.862,4560.187,4174.501,4134.044],"text":["Age: 51-55<br />sum_p_thous: $11,669.24<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $5,671.86<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $4,560.19<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $4,174.50<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $4,134.04<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x3","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[6,6,6,6,6],"y":[34528.511,12388.376,10067.865,9319.469,9099.449],"text":["Age: 51-55<br />sum_p_thous: $34,528.51<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $12,388.38<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $10,067.86<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $9,319.47<br />Age: 51-55","Age: 51-55<br />sum_p_thous: $9,099.45<br />Age: 51-55"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"51-55","legendgroup":"51-55","showlegend":false,"xaxis":"x4","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[7,7,7,7],"y":[905.517,510.992,381.019,183.513],"text":["Age: 55+<br />sum_p_thous: $905.52<br />Age: 55+","Age: 55+<br />sum_p_thous: $510.99<br />Age: 55+","Age: 55+<br />sum_p_thous: $381.02<br />Age: 55+","Age: 55+<br />sum_p_thous: $183.51<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9],"base":[0,0,0],"x":[7,7,7],"y":[630.829,413.775,276.049],"text":["Age: 55+<br />sum_p_thous: $630.83<br />Age: 55+","Age: 55+<br />sum_p_thous: $413.77<br />Age: 55+","Age: 55+<br />sum_p_thous: $276.05<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[5658.378,2290.182,2103.77,866.409,351.963],"text":["Age: 55+<br />sum_p_thous: $5,658.38<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,290.18<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,103.77<br />Age: 55+","Age: 55+<br />sum_p_thous: $866.41<br />Age: 55+","Age: 55+<br />sum_p_thous: $351.96<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x3","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[7134.366,3630.948,2148.019,1895.144,588.13],"text":["Age: 55+<br />sum_p_thous: $7,134.37<br />Age: 55+","Age: 55+<br />sum_p_thous: $3,630.95<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,148.02<br />Age: 55+","Age: 55+<br />sum_p_thous: $1,895.14<br />Age: 55+","Age: 55+<br />sum_p_thous: $588.13<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x4","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9],"base":[0,0,0],"x":[7,7,7],"y":[1588.222,1356.409,639.125],"text":["Age: 55+<br />sum_p_thous: $1,588.22<br />Age: 55+","Age: 55+<br />sum_p_thous: $1,356.41<br />Age: 55+","Age: 55+<br />sum_p_thous: $639.12<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9],"base":[0,0,0,0],"x":[7,7,7,7],"y":[4093.34,2323.081,1353.424,568.343],"text":["Age: 55+<br />sum_p_thous: $4,093.34<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,323.08<br />Age: 55+","Age: 55+<br />sum_p_thous: $1,353.42<br />Age: 55+","Age: 55+<br />sum_p_thous: $568.34<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[7715.372,2566.672,2112.373,714.804,307.339],"text":["Age: 55+<br />sum_p_thous: $7,715.37<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,566.67<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,112.37<br />Age: 55+","Age: 55+<br />sum_p_thous: $714.80<br />Age: 55+","Age: 55+<br />sum_p_thous: $307.34<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x3","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[6113.071,5796.683,4275.453,4206.461,3977.932],"text":["Age: 55+<br />sum_p_thous: $6,113.07<br />Age: 55+","Age: 55+<br />sum_p_thous: $5,796.68<br />Age: 55+","Age: 55+<br />sum_p_thous: $4,275.45<br />Age: 55+","Age: 55+<br />sum_p_thous: $4,206.46<br />Age: 55+","Age: 55+<br />sum_p_thous: $3,977.93<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x4","yaxis":"y2","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[4042.384,3350.393,1365.18,1360.022,835.427],"text":["Age: 55+<br />sum_p_thous: $4,042.38<br />Age: 55+","Age: 55+<br />sum_p_thous: $3,350.39<br />Age: 55+","Age: 55+<br />sum_p_thous: $1,365.18<br />Age: 55+","Age: 55+<br />sum_p_thous: $1,360.02<br />Age: 55+","Age: 55+<br />sum_p_thous: $835.43<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[6771.579,5788.123,2141.123,2139.161,1933.366],"text":["Age: 55+<br />sum_p_thous: $6,771.58<br />Age: 55+","Age: 55+<br />sum_p_thous: $5,788.12<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,141.12<br />Age: 55+","Age: 55+<br />sum_p_thous: $2,139.16<br />Age: 55+","Age: 55+<br />sum_p_thous: $1,933.37<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x2","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[13390.485,6464.229,6299.945,3196.355,3148.529],"text":["Age: 55+<br />sum_p_thous: $13,390.49<br />Age: 55+","Age: 55+<br />sum_p_thous: $6,464.23<br />Age: 55+","Age: 55+<br />sum_p_thous: $6,299.94<br />Age: 55+","Age: 55+<br />sum_p_thous: $3,196.36<br />Age: 55+","Age: 55+<br />sum_p_thous: $3,148.53<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x3","yaxis":"y3","hoverinfo":"text","frame":null},{"orientation":"v","width":[0.9,0.9,0.9,0.9,0.9],"base":[0,0,0,0,0],"x":[7,7,7,7,7],"y":[20131.054,12453.561,8693.552,8582.853,5850.414],"text":["Age: 55+<br />sum_p_thous: $20,131.05<br />Age: 55+","Age: 55+<br />sum_p_thous: $12,453.56<br />Age: 55+","Age: 55+<br />sum_p_thous: $8,693.55<br />Age: 55+","Age: 55+<br />sum_p_thous: $8,582.85<br />Age: 55+","Age: 55+<br />sum_p_thous: $5,850.41<br />Age: 55+"],"type":"bar","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"55+","legendgroup":"55+","showlegend":false,"xaxis":"x4","yaxis":"y3","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":51.4195576113384,"r":18.9954337899543,"b":36.1501512186444,"l":49.4811124948111},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":"Наиболее платёжеспособная аудитория (Рис. 18)","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"xaxis":{"domain":[0,0.244232155731795],"automargin":true,"type":"linear","autorange":false,"range":[0.4,7.6],"tickmode":"array","ticktext":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"tickvals":[1,2,3,4,5,6,7],"categoryorder":"array","categoryarray":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":7.97011207970112},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y3","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"annotations":[{"text":"Возраст","x":0.5,"y":-0.0202810887742395,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"top","annotationType":"axis"},{"text":"Сумма покупок","x":-0.0275283476437045,"y":0.5,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-90,"xanchor":"right","yanchor":"center","annotationType":"axis"},{"text":"Female<br />Not Married","x":0.122116077865898,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":7.97011207970112},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Female<br />Married","x":0.375,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":7.97011207970112},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Male<br />Not Married","x":0.625,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":7.97011207970112},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Male<br />Married","x":0.877883922134102,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":7.97011207970112},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"A","x":1,"y":0.837247227658187,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":90,"xanchor":"left","yanchor":"middle"},{"text":"B","x":1,"y":0.5,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":90,"xanchor":"left","yanchor":"middle"},{"text":"C","x":1,"y":0.162752772341813,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":11.689497716895},"xref":"paper","yref":"paper","textangle":90,"xanchor":"left","yanchor":"middle"}],"yaxis":{"domain":[0.674494455316373,1],"automargin":true,"type":"linear","autorange":false,"range":[-7500,157500],"tickmode":"array","ticktext":["0","20000","40000","60000","80000","100000","120000","140000"],"tickvals":[0,20000,40000,60000,80000,100000,120000,140000],"categoryorder":"array","categoryarray":["0","20000","40000","60000","80000","100000","120000","140000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":7.97011207970112},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.244232155731795,"y0":0.674494455316373,"y1":1},{"type":"rect","fillcolor":"rgba(217,217,217,1)","line":{"color":"transparent","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":0.244232155731795,"y0":0,"y1":19.6596097965961,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.255767844268205,"x1":0.494232155731795,"y0":0.674494455316373,"y1":1},{"type":"rect","fillcolor":"rgba(217,217,217,1)","line":{"color":"transparent","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.255767844268205,"x1":0.494232155731795,"y0":0,"y1":19.6596097965961,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.505767844268205,"x1":0.744232155731795,"y0":0.674494455316373,"y1":1},{"type":"rect","fillcolor":"rgba(217,217,217,1)","line":{"color":"transparent","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.505767844268205,"x1":0.744232155731795,"y0":0,"y1":19.6596097965961,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.755767844268205,"x1":1,"y0":0.674494455316373,"y1":1},{"type":"rect","fillcolor":"rgba(217,217,217,1)","line":{"color":"transparent","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0.755767844268205,"x1":1,"y0":0,"y1":19.6596097965961,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":"rgba(217,217,217,1)","line":{"color":"transparent","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","y0":0.674494455316373,"y1":1,"x0":0,"x1":23.37899543379,"xanchor":1,"xsizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.244232155731795,"y0":0.34116112198304,"y1":0.65883887801696},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.255767844268205,"x1":0.494232155731795,"y0":0.34116112198304,"y1":0.65883887801696},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.505767844268205,"x1":0.744232155731795,"y0":0.34116112198304,"y1":0.65883887801696},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.755767844268205,"x1":1,"y0":0.34116112198304,"y1":0.65883887801696},{"type":"rect","fillcolor":"rgba(217,217,217,1)","line":{"color":"transparent","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","y0":0.34116112198304,"y1":0.65883887801696,"x0":0,"x1":23.37899543379,"xanchor":1,"xsizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":0.244232155731795,"y0":0,"y1":0.325505544683627},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.255767844268205,"x1":0.494232155731795,"y0":0,"y1":0.325505544683627},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.505767844268205,"x1":0.744232155731795,"y0":0,"y1":0.325505544683627},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0.755767844268205,"x1":1,"y0":0,"y1":0.325505544683627},{"type":"rect","fillcolor":"rgba(217,217,217,1)","line":{"color":"transparent","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","y0":0,"y1":0.325505544683627,"x0":0,"x1":23.37899543379,"xanchor":1,"xsizemode":"pixel"}],"xaxis2":{"type":"linear","autorange":false,"range":[0.4,7.6],"tickmode":"array","ticktext":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"tickvals":[1,2,3,4,5,6,7],"categoryorder":"array","categoryarray":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":7.97011207970112},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.255767844268205,0.494232155731795],"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y3","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"xaxis3":{"type":"linear","autorange":false,"range":[0.4,7.6],"tickmode":"array","ticktext":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"tickvals":[1,2,3,4,5,6,7],"categoryorder":"array","categoryarray":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":7.97011207970112},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.505767844268205,0.744232155731795],"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y3","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"xaxis4":{"type":"linear","autorange":false,"range":[0.4,7.6],"tickmode":"array","ticktext":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"tickvals":[1,2,3,4,5,6,7],"categoryorder":"array","categoryarray":["0-17","18-25","26-35","36-45","46-50","51-55","55+"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":7.97011207970112},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.755767844268205,1],"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y3","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"yaxis2":{"type":"linear","autorange":false,"range":[-7500,157500],"tickmode":"array","ticktext":["0","20000","40000","60000","80000","100000","120000","140000"],"tickvals":[0,20000,40000,60000,80000,100000,120000,140000],"categoryorder":"array","categoryarray":["0","20000","40000","60000","80000","100000","120000","140000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":7.97011207970112},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.34116112198304,0.65883887801696],"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"yaxis3":{"type":"linear","autorange":false,"range":[-7500,157500],"tickmode":"array","ticktext":["0","20000","40000","60000","80000","100000","120000","140000"],"tickvals":[0,20000,40000,60000,80000,100000,120000,140000],"categoryorder":"array","categoryarray":["0","20000","40000","60000","80000","100000","120000","140000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":7.97011207970112},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0,0.325505544683627],"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895},"y":1},"hovermode":"closest","width":950,"height":700,"barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"source":"A","attrs":{"181b41f299c4":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"181b41f299c4","visdat":{"181b41f299c4":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><!--/html_preserve-->

На графике (Рис. 18) мы видим, что с точки зрения выручки самая привлекательная для нас аудитория -- неженатые мужчины 26-35 лет из города категории B.

Убедимся в этом и для удобства упорядочим график и выстроим все категории людей в единую линию:
<!--html_preserve--><div id="htmlwidget-f8b01bde1b4c31755e64" style="width:950px;height:700px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-f8b01bde1b4c31755e64">{"x":{"data":[{"orientation":"v","width":0.9,"base":0,"x":[1],"y":[392550.353],"text":"users: Not Married, Male, 26-35, B<br />sum_p_thous: $392,550.35<br />users: Not Married, Male, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 26-35, B","legendgroup":"Not Married, Male, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[2],"y":[317679.455],"text":"users: Not Married, Male, 26-35, A<br />sum_p_thous: $317,679.46<br />users: Not Married, Male, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(245,122,96,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 26-35, A","legendgroup":"Not Married, Male, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[3],"y":[253135.896],"text":"users: Married, Male, 26-35, B<br />sum_p_thous: $253,135.90<br />users: Married, Male, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(242,125,82,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 26-35, B","legendgroup":"Married, Male, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[4],"y":[243355.515],"text":"users: Not Married, Male, 26-35, C<br />sum_p_thous: $243,355.51<br />users: Not Married, Male, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(238,128,67,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 26-35, C","legendgroup":"Not Married, Male, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[5],"y":[232940.505],"text":"users: Not Married, Male, 18-25, B<br />sum_p_thous: $232,940.51<br />users: Not Married, Male, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(234,132,47,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 18-25, B","legendgroup":"Not Married, Male, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[6],"y":[214764.859],"text":"users: Not Married, Male, 36-45, B<br />sum_p_thous: $214,764.86<br />users: Not Married, Male, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(230,135,11,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 36-45, B","legendgroup":"Not Married, Male, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[7],"y":[177644.373],"text":"users: Married, Male, 26-35, C<br />sum_p_thous: $177,644.37<br />users: Married, Male, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(225,138,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 26-35, C","legendgroup":"Married, Male, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[8],"y":[175868.745],"text":"users: Not Married, Male, 18-25, C<br />sum_p_thous: $175,868.74<br />users: Not Married, Male, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(220,141,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 18-25, C","legendgroup":"Not Married, Male, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[9],"y":[165249.097],"text":"users: Married, Male, 26-35, A<br />sum_p_thous: $165,249.10<br />users: Married, Male, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(215,144,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 26-35, A","legendgroup":"Married, Male, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[10],"y":[159023.803],"text":"users: Not Married, Male, 36-45, C<br />sum_p_thous: $159,023.80<br />users: Not Married, Male, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(209,147,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 36-45, C","legendgroup":"Not Married, Male, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[11],"y":[152454.384],"text":"users: Not Married, Male, 18-25, A<br />sum_p_thous: $152,454.38<br />users: Not Married, Male, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(203,150,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 18-25, A","legendgroup":"Not Married, Male, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[12],"y":[117478.737],"text":"users: Not Married, Female, 26-35, B<br />sum_p_thous: $117,478.74<br />users: Not Married, Female, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(197,153,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 26-35, B","legendgroup":"Not Married, Female, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[13],"y":[116338.388],"text":"users: Married, Male, 36-45, B<br />sum_p_thous: $116,338.39<br />users: Married, Male, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(190,156,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 36-45, B","legendgroup":"Married, Male, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[14],"y":[106289.326],"text":"users: Married, Male, 36-45, C<br />sum_p_thous: $106,289.33<br />users: Married, Male, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(183,159,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 36-45, C","legendgroup":"Married, Male, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[15],"y":[100661.234],"text":"users: Married, Male, 46-50, B<br />sum_p_thous: $100,661.23<br />users: Married, Male, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(176,161,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 46-50, B","legendgroup":"Married, Male, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[16],"y":[99072.104],"text":"users: Married, Male, 51-55, B<br />sum_p_thous: $99,072.10<br />users: Married, Male, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(168,164,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 51-55, B","legendgroup":"Married, Male, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[17],"y":[83756.294],"text":"users: Not Married, Female, 26-35, A<br />sum_p_thous: $83,756.29<br />users: Not Married, Female, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(159,166,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 26-35, A","legendgroup":"Not Married, Female, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[18],"y":[82777.665],"text":"users: Not Married, Male, 36-45, A<br />sum_p_thous: $82,777.66<br />users: Not Married, Male, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(150,169,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 36-45, A","legendgroup":"Not Married, Male, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[19],"y":[81908.261],"text":"users: Married, Male, 36-45, A<br />sum_p_thous: $81,908.26<br />users: Married, Male, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(140,171,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 36-45, A","legendgroup":"Married, Male, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[20],"y":[78453.397],"text":"users: Married, Male, 46-50, C<br />sum_p_thous: $78,453.40<br />users: Married, Male, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(129,173,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 46-50, C","legendgroup":"Married, Male, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[21],"y":[75403.67],"text":"users: Married, Male, 51-55, C<br />sum_p_thous: $75,403.67<br />users: Married, Male, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(117,175,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 51-55, C","legendgroup":"Married, Male, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[22],"y":[68034.848],"text":"users: Not Married, Female, 18-25, B<br />sum_p_thous: $68,034.85<br />users: Not Married, Female, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(104,177,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 18-25, B","legendgroup":"Not Married, Female, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[23],"y":[64767.089],"text":"users: Married, Female, 26-35, A<br />sum_p_thous: $64,767.09<br />users: Married, Female, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(88,179,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 26-35, A","legendgroup":"Married, Female, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[24],"y":[62614.964],"text":"users: Married, Female, 26-35, B<br />sum_p_thous: $62,614.96<br />users: Married, Female, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(68,181,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 26-35, B","legendgroup":"Married, Female, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[25],"y":[59827.314],"text":"users: Married, Male, 18-25, B<br />sum_p_thous: $59,827.31<br />users: Married, Male, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(36,183,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 18-25, B","legendgroup":"Married, Male, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[26],"y":[57529.348],"text":"users: Not Married, Female, 36-45, B<br />sum_p_thous: $57,529.35<br />users: Not Married, Female, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,184,33,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 36-45, B","legendgroup":"Not Married, Female, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[27],"y":[55711.434],"text":"users: Married, Male, 55+, C<br />sum_p_thous: $55,711.43<br />users: Married, Male, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 55+, C","legendgroup":"Married, Male, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[28],"y":[53229.617],"text":"users: Not Married, Female, 26-35, C<br />sum_p_thous: $53,229.62<br />users: Not Married, Female, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,187,73,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 26-35, C","legendgroup":"Not Married, Female, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[29],"y":[52010.979],"text":"users: Married, Female, 26-35, C<br />sum_p_thous: $52,010.98<br />users: Married, Female, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,188,88,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 26-35, C","legendgroup":"Married, Female, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[30],"y":[49920.974],"text":"users: Not Married, Female, 36-45, C<br />sum_p_thous: $49,920.97<br />users: Not Married, Female, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,189,100,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 36-45, C","legendgroup":"Not Married, Female, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[31],"y":[46654.407],"text":"users: Not Married, Male, 0-17, C<br />sum_p_thous: $46,654.41<br />users: Not Married, Male, 0-17, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,190,112,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 0-17, C","legendgroup":"Not Married, Male, 0-17, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000002,"base":0,"x":[32],"y":[45357.098],"text":"users: Not Married, Female, 18-25, C<br />sum_p_thous: $45,357.10<br />users: Not Married, Female, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,191,123,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 18-25, C","legendgroup":"Not Married, Female, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[33],"y":[42438.83],"text":"users: Married, Female, 46-50, B<br />sum_p_thous: $42,438.83<br />users: Married, Female, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,134,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 46-50, B","legendgroup":"Married, Female, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[34],"y":[40942.042],"text":"users: Not Married, Female, 36-45, A<br />sum_p_thous: $40,942.04<br />users: Not Married, Female, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,144,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 36-45, A","legendgroup":"Not Married, Female, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[35],"y":[40868.957],"text":"users: Married, Male, 18-25, C<br />sum_p_thous: $40,868.96<br />users: Married, Male, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,193,153,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 18-25, C","legendgroup":"Married, Male, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[36],"y":[39913.232],"text":"users: Not Married, Female, 18-25, A<br />sum_p_thous: $39,913.23<br />users: Not Married, Female, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,193,162,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 18-25, A","legendgroup":"Not Married, Female, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[37],"y":[37818.169],"text":"users: Married, Female, 36-45, B<br />sum_p_thous: $37,818.17<br />users: Married, Female, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,193,171,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 36-45, B","legendgroup":"Married, Female, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[38],"y":[37684.967],"text":"users: Not Married, Male, 46-50, C<br />sum_p_thous: $37,684.97<br />users: Not Married, Male, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,180,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 46-50, C","legendgroup":"Not Married, Male, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[39],"y":[37499.925],"text":"users: Married, Male, 18-25, A<br />sum_p_thous: $37,499.93<br />users: Married, Male, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,188,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 18-25, A","legendgroup":"Married, Male, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[40],"y":[36825.446],"text":"users: Married, Female, 46-50, C<br />sum_p_thous: $36,825.45<br />users: Married, Female, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,191,196,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 46-50, C","legendgroup":"Married, Female, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[41],"y":[35198.371],"text":"users: Married, Male, 46-50, A<br />sum_p_thous: $35,198.37<br />users: Married, Male, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,190,204,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 46-50, A","legendgroup":"Married, Male, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[42],"y":[33782.97],"text":"users: Not Married, Male, 0-17, B<br />sum_p_thous: $33,782.97<br />users: Not Married, Male, 0-17, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,189,211,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 0-17, B","legendgroup":"Not Married, Male, 0-17, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[43],"y":[32598.103],"text":"users: Married, Female, 36-45, C<br />sum_p_thous: $32,598.10<br />users: Married, Female, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,187,218,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 36-45, C","legendgroup":"Married, Female, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[44],"y":[32499.543],"text":"users: Not Married, Male, 55+, C<br />sum_p_thous: $32,499.54<br />users: Not Married, Male, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,186,225,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 55+, C","legendgroup":"Not Married, Male, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[45],"y":[30209.838],"text":"users: Not Married, Male, 51-55, C<br />sum_p_thous: $30,209.84<br />users: Not Married, Male, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,183,231,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 51-55, C","legendgroup":"Not Married, Male, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[46],"y":[29878.325],"text":"users: Not Married, Male, 46-50, B<br />sum_p_thous: $29,878.33<br />users: Not Married, Male, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,181,237,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 46-50, B","legendgroup":"Not Married, Male, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[47],"y":[28843.388],"text":"users: Married, Male, 51-55, A<br />sum_p_thous: $28,843.39<br />users: Married, Male, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,178,243,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 51-55, A","legendgroup":"Married, Male, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[48],"y":[27380.753],"text":"users: Not Married, Male, 51-55, B<br />sum_p_thous: $27,380.75<br />users: Not Married, Male, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,175,247,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 51-55, B","legendgroup":"Not Married, Male, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[49],"y":[24380.364],"text":"users: Married, Female, 18-25, B<br />sum_p_thous: $24,380.36<br />users: Married, Female, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,172,252,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 18-25, B","legendgroup":"Married, Female, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[50],"y":[24369.6],"text":"users: Married, Male, 55+, B<br />sum_p_thous: $24,369.60<br />users: Married, Male, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,168,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 55+, B","legendgroup":"Married, Male, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[51],"y":[23587.751],"text":"users: Married, Female, 51-55, C<br />sum_p_thous: $23,587.75<br />users: Married, Female, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,165,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 51-55, C","legendgroup":"Married, Female, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[52],"y":[20717.172],"text":"users: Married, Female, 51-55, B<br />sum_p_thous: $20,717.17<br />users: Married, Female, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(66,160,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 51-55, B","legendgroup":"Married, Female, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[53],"y":[20201.844],"text":"users: Married, Female, 36-45, A<br />sum_p_thous: $20,201.84<br />users: Married, Female, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 36-45, A","legendgroup":"Married, Female, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[54],"y":[18773.352],"text":"users: Married, Female, 55+, C<br />sum_p_thous: $18,773.35<br />users: Married, Female, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(120,151,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 55+, C","legendgroup":"Married, Female, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[55],"y":[16833.598],"text":"users: Not Married, Female, 0-17, C<br />sum_p_thous: $16,833.60<br />users: Not Married, Female, 0-17, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(139,147,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 0-17, C","legendgroup":"Not Married, Female, 0-17, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[56],"y":[16744.936],"text":"users: Not Married, Male, 46-50, A<br />sum_p_thous: $16,744.94<br />users: Not Married, Male, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(155,142,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 46-50, A","legendgroup":"Not Married, Male, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[57],"y":[16613.868],"text":"users: Not Married, Female, 51-55, B<br />sum_p_thous: $16,613.87<br />users: Not Married, Female, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(169,137,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 51-55, B","legendgroup":"Not Married, Female, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[58],"y":[15396.607],"text":"users: Married, Male, 55+, A<br />sum_p_thous: $15,396.61<br />users: Married, Male, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(182,132,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 55+, A","legendgroup":"Married, Male, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[59],"y":[14221.461],"text":"users: Married, Female, 18-25, C<br />sum_p_thous: $14,221.46<br />users: Married, Female, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(194,127,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 18-25, C","legendgroup":"Married, Female, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[60],"y":[13730.812],"text":"users: Not Married, Female, 0-17, B<br />sum_p_thous: $13,730.81<br />users: Not Married, Female, 0-17, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(204,122,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 0-17, B","legendgroup":"Not Married, Female, 0-17, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[61],"y":[13416.56],"text":"users: Not Married, Male, 55+, B<br />sum_p_thous: $13,416.56<br />users: Not Married, Male, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(213,117,254,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 55+, B","legendgroup":"Not Married, Male, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[62],"y":[13026.196],"text":"users: Not Married, Male, 51-55, A<br />sum_p_thous: $13,026.20<br />users: Not Married, Male, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(221,113,250,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 51-55, A","legendgroup":"Not Married, Male, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[63],"y":[12820.894],"text":"users: Not Married, Female, 46-50, C<br />sum_p_thous: $12,820.89<br />users: Not Married, Female, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(229,109,245,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 46-50, C","legendgroup":"Not Married, Female, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[64],"y":[12033.695],"text":"users: Not Married, Female, 46-50, B<br />sum_p_thous: $12,033.69<br />users: Not Married, Female, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(235,105,240,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 46-50, B","legendgroup":"Not Married, Female, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[65],"y":[11767.315],"text":"users: Not Married, Female, 51-55, C<br />sum_p_thous: $11,767.32<br />users: Not Married, Female, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(240,102,234,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 51-55, C","legendgroup":"Not Married, Female, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[66],"y":[11472.084],"text":"users: Married, Female, 51-55, A<br />sum_p_thous: $11,472.08<br />users: Married, Female, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(245,100,227,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 51-55, A","legendgroup":"Married, Female, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[67],"y":[11270.702],"text":"users: Not Married, Male, 55+, A<br />sum_p_thous: $11,270.70<br />users: Not Married, Male, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(249,98,221,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 55+, A","legendgroup":"Not Married, Male, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[68],"y":[11262.205],"text":"users: Not Married, Female, 0-17, A<br />sum_p_thous: $11,262.20<br />users: Not Married, Female, 0-17, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(252,97,213,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 0-17, A","legendgroup":"Not Married, Female, 0-17, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[69],"y":[10953.406],"text":"users: Not Married, Female, 55+, C<br />sum_p_thous: $10,953.41<br />users: Not Married, Female, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(254,97,206,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 55+, C","legendgroup":"Not Married, Female, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[70],"y":[10395.014],"text":"users: Not Married, Male, 0-17, A<br />sum_p_thous: $10,395.01<br />users: Not Married, Male, 0-17, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,97,198,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 0-17, A","legendgroup":"Not Married, Male, 0-17, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[71],"y":[10302.447],"text":"users: Married, Female, 18-25, A<br />sum_p_thous: $10,302.45<br />users: Married, Female, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,98,189,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 18-25, A","legendgroup":"Married, Female, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[72],"y":[8419.408],"text":"users: Married, Female, 46-50, A<br />sum_p_thous: $8,419.41<br />users: Married, Female, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,99,181,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 46-50, A","legendgroup":"Married, Female, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[73],"y":[8338.188],"text":"users: Married, Female, 55+, B<br />sum_p_thous: $8,338.19<br />users: Married, Female, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,101,172,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 55+, B","legendgroup":"Married, Female, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[74],"y":[3814.217],"text":"users: Not Married, Female, 51-55, A<br />sum_p_thous: $3,814.22<br />users: Not Married, Female, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,103,162,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 51-55, A","legendgroup":"Not Married, Female, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[75],"y":[3583.756],"text":"users: Not Married, Female, 55+, B<br />sum_p_thous: $3,583.76<br />users: Not Married, Female, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,106,153,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 55+, B","legendgroup":"Not Married, Female, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[76],"y":[2258.72],"text":"users: Not Married, Female, 46-50, A<br />sum_p_thous: $2,258.72<br />users: Not Married, Female, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,109,142,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 46-50, A","legendgroup":"Not Married, Female, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[77],"y":[1981.041],"text":"users: Not Married, Female, 55+, A<br />sum_p_thous: $1,981.04<br />users: Not Married, Female, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(253,112,132,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 55+, A","legendgroup":"Not Married, Female, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[78],"y":[1320.653],"text":"users: Married, Female, 55+, A<br />sum_p_thous: $1,320.65<br />users: Married, Female, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(250,115,121,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 55+, A","legendgroup":"Married, Female, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.4494455316373,"r":7.30593607305936,"b":28.1800391389433,"l":60.6392694063927},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":"Наиболее платёжеспособная аудитория (Рис. 19)","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,78.6],"tickmode":"array","ticktext":["Not Married, Male, 26-35, B","Not Married, Male, 26-35, A","Married, Male, 26-35, B","Not Married, Male, 26-35, C","Not Married, Male, 18-25, B","Not Married, Male, 36-45, B","Married, Male, 26-35, C","Not Married, Male, 18-25, C","Married, Male, 26-35, A","Not Married, Male, 36-45, C","Not Married, Male, 18-25, A","Not Married, Female, 26-35, B","Married, Male, 36-45, B","Married, Male, 36-45, C","Married, Male, 46-50, B","Married, Male, 51-55, B","Not Married, Female, 26-35, A","Not Married, Male, 36-45, A","Married, Male, 36-45, A","Married, Male, 46-50, C","Married, Male, 51-55, C","Not Married, Female, 18-25, B","Married, Female, 26-35, A","Married, Female, 26-35, B","Married, Male, 18-25, B","Not Married, Female, 36-45, B","Married, Male, 55+, C","Not Married, Female, 26-35, C","Married, Female, 26-35, C","Not Married, Female, 36-45, C","Not Married, Male, 0-17, C","Not Married, Female, 18-25, C","Married, Female, 46-50, B","Not Married, Female, 36-45, A","Married, Male, 18-25, C","Not Married, Female, 18-25, A","Married, Female, 36-45, B","Not Married, Male, 46-50, C","Married, Male, 18-25, A","Married, Female, 46-50, C","Married, Male, 46-50, A","Not Married, Male, 0-17, B","Married, Female, 36-45, C","Not Married, Male, 55+, C","Not Married, Male, 51-55, C","Not Married, Male, 46-50, B","Married, Male, 51-55, A","Not Married, Male, 51-55, B","Married, Female, 18-25, B","Married, Male, 55+, B","Married, Female, 51-55, C","Married, Female, 51-55, B","Married, Female, 36-45, A","Married, Female, 55+, C","Not Married, Female, 0-17, C","Not Married, Male, 46-50, A","Not Married, Female, 51-55, B","Married, Male, 55+, A","Married, Female, 18-25, C","Not Married, Female, 0-17, B","Not Married, Male, 55+, B","Not Married, Male, 51-55, A","Not Married, Female, 46-50, C","Not Married, Female, 46-50, B","Not Married, Female, 51-55, C","Married, Female, 51-55, A","Not Married, Male, 55+, A","Not Married, Female, 0-17, A","Not Married, Female, 55+, C","Not Married, Male, 0-17, A","Married, Female, 18-25, A","Married, Female, 46-50, A","Married, Female, 55+, B","Not Married, Female, 51-55, A","Not Married, Female, 55+, B","Not Married, Female, 46-50, A","Not Married, Female, 55+, A","Married, Female, 55+, A"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78],"categoryorder":"array","categoryarray":["Not Married, Male, 26-35, B","Not Married, Male, 26-35, A","Married, Male, 26-35, B","Not Married, Male, 26-35, C","Not Married, Male, 18-25, B","Not Married, Male, 36-45, B","Married, Male, 26-35, C","Not Married, Male, 18-25, C","Married, Male, 26-35, A","Not Married, Male, 36-45, C","Not Married, Male, 18-25, A","Not Married, Female, 26-35, B","Married, Male, 36-45, B","Married, Male, 36-45, C","Married, Male, 46-50, B","Married, Male, 51-55, B","Not Married, Female, 26-35, A","Not Married, Male, 36-45, A","Married, Male, 36-45, A","Married, Male, 46-50, C","Married, Male, 51-55, C","Not Married, Female, 18-25, B","Married, Female, 26-35, A","Married, Female, 26-35, B","Married, Male, 18-25, B","Not Married, Female, 36-45, B","Married, Male, 55+, C","Not Married, Female, 26-35, C","Married, Female, 26-35, C","Not Married, Female, 36-45, C","Not Married, Male, 0-17, C","Not Married, Female, 18-25, C","Married, Female, 46-50, B","Not Married, Female, 36-45, A","Married, Male, 18-25, C","Not Married, Female, 18-25, A","Married, Female, 36-45, B","Not Married, Male, 46-50, C","Married, Male, 18-25, A","Married, Female, 46-50, C","Married, Male, 46-50, A","Not Married, Male, 0-17, B","Married, Female, 36-45, C","Not Married, Male, 55+, C","Not Married, Male, 51-55, C","Not Married, Male, 46-50, B","Married, Male, 51-55, A","Not Married, Male, 51-55, B","Married, Female, 18-25, B","Married, Male, 55+, B","Married, Female, 51-55, C","Married, Female, 51-55, B","Married, Female, 36-45, A","Married, Female, 55+, C","Not Married, Female, 0-17, C","Not Married, Male, 46-50, A","Not Married, Female, 51-55, B","Married, Male, 55+, A","Married, Female, 18-25, C","Not Married, Female, 0-17, B","Not Married, Male, 55+, B","Not Married, Male, 51-55, A","Not Married, Female, 46-50, C","Not Married, Female, 46-50, B","Not Married, Female, 51-55, C","Married, Female, 51-55, A","Not Married, Male, 55+, A","Not Married, Female, 0-17, A","Not Married, Female, 55+, C","Not Married, Male, 0-17, A","Married, Female, 18-25, A","Married, Female, 46-50, A","Married, Female, 55+, B","Not Married, Female, 51-55, A","Not Married, Female, 55+, B","Not Married, Female, 46-50, A","Not Married, Female, 55+, A","Married, Female, 55+, A"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":false,"tickfont":{"color":null,"family":null,"size":0},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":"Группа пользователей","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-19627.51765,412177.87065],"tickmode":"array","ticktext":["0","10000","20000","30000","40000","50000","60000","70000","80000","90000","100000","110000","120000","130000","140000","150000","160000","170000","180000","190000","200000","210000","220000","230000","240000","250000","260000","270000","280000","290000","300000","310000","320000","330000","340000","350000","360000","370000","380000","390000","400000","410000"],"tickvals":[0,10000,20000,30000,40000,50000,60000,70000,80000,90000,100000,110000,120000,130000,140000,150000,160000,170000,180000,190000,200000,210000,220000,230000,240000,250000,260000,270000,280000,290000,300000,310000,320000,330000,340000,350000,360000,370000,380000,390000,400000,410000],"categoryorder":"array","categoryarray":["0","10000","20000","30000","40000","50000","60000","70000","80000","90000","100000","110000","120000","130000","140000","150000","160000","170000","180000","190000","200000","210000","220000","230000","240000","250000","260000","270000","280000","290000","300000","310000","320000","330000","340000","350000","360000","370000","380000","390000","400000","410000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"Сумма покупок","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895},"y":1},"hovermode":"closest","width":950,"height":700,"barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"source":"A","attrs":{"181b51eab1a7":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"181b51eab1a7","visdat":{"181b51eab1a7":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><!--/html_preserve-->

C точки зрения абсолютного дохода самыми привлекательными являются: **Not Married, Male, 26-35, B, Not Married, Male, 26-35, A, Married, Male, 26-35, B**.

Если же смотреть на метрику "доход на пользователя", которая учитывает то, сколько людей находится в каждом типе города, то увидим другую картину:
<!--html_preserve--><div id="htmlwidget-15939223f41b7c24f3fc" style="width:950px;height:700px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-15939223f41b7c24f3fc">{"x":{"data":[{"orientation":"v","width":0.9,"base":0,"x":[1],"y":[10.4939637138856],"text":"users: Not Married, Male, 51-55, C<br />avg_purch_per_order: $10.49<br />users: Not Married, Male, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 51-55, C","legendgroup":"Not Married, Male, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[2],"y":[10.3250482056759],"text":"users: Married, Male, 36-45, C<br />avg_purch_per_order: $10.33<br />users: Married, Male, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(245,122,96,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 36-45, C","legendgroup":"Married, Male, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[3],"y":[10.2907607067045],"text":"users: Not Married, Male, 51-55, A<br />avg_purch_per_order: $10.29<br />users: Not Married, Male, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(242,125,82,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 51-55, A","legendgroup":"Not Married, Male, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[4],"y":[10.1966389693002],"text":"users: Married, Male, 18-25, C<br />avg_purch_per_order: $10.20<br />users: Married, Male, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(238,128,67,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 18-25, C","legendgroup":"Married, Male, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[5],"y":[10.1801534434096],"text":"users: Married, Male, 26-35, C<br />avg_purch_per_order: $10.18<br />users: Married, Male, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(234,132,47,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 26-35, C","legendgroup":"Married, Male, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[6],"y":[10.128915743817],"text":"users: Not Married, Male, 26-35, C<br />avg_purch_per_order: $10.13<br />users: Not Married, Male, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(230,135,11,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 26-35, C","legendgroup":"Not Married, Male, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.9,"base":0,"x":[7],"y":[10.0984310384612],"text":"users: Married, Female, 46-50, A<br />avg_purch_per_order: $10.10<br />users: Married, Female, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(225,138,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 46-50, A","legendgroup":"Married, Female, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[8],"y":[10.09801920373],"text":"users: Not Married, Male, 36-45, C<br />avg_purch_per_order: $10.10<br />users: Not Married, Male, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(220,141,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 36-45, C","legendgroup":"Not Married, Male, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[9],"y":[10.0629936394664],"text":"users: Not Married, Male, 18-25, C<br />avg_purch_per_order: $10.06<br />users: Not Married, Male, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(215,144,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 18-25, C","legendgroup":"Not Married, Male, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[10],"y":[10.0268827930658],"text":"users: Married, Male, 51-55, C<br />avg_purch_per_order: $10.03<br />users: Married, Male, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(209,147,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 51-55, C","legendgroup":"Married, Male, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[11],"y":[9.99882674982757],"text":"users: Not Married, Male, 55+, B<br />avg_purch_per_order: $10.00<br />users: Not Married, Male, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(203,150,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 55+, B","legendgroup":"Not Married, Male, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[12],"y":[9.93246876070022],"text":"users: Not Married, Female, 55+, A<br />avg_purch_per_order: $9.93<br />users: Not Married, Female, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(197,153,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 55+, A","legendgroup":"Not Married, Female, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[13],"y":[9.92180467269107],"text":"users: Married, Male, 46-50, C<br />avg_purch_per_order: $9.92<br />users: Married, Male, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(190,156,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 46-50, C","legendgroup":"Married, Male, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[14],"y":[9.91109716622945],"text":"users: Not Married, Male, 36-45, A<br />avg_purch_per_order: $9.91<br />users: Not Married, Male, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(183,159,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 36-45, A","legendgroup":"Not Married, Male, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[15],"y":[9.83675149218685],"text":"users: Not Married, Male, 55+, C<br />avg_purch_per_order: $9.84<br />users: Not Married, Male, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(176,161,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 55+, C","legendgroup":"Not Married, Male, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[16],"y":[9.82606893030216],"text":"users: Not Married, Male, 0-17, A<br />avg_purch_per_order: $9.83<br />users: Not Married, Male, 0-17, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(168,164,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 0-17, A","legendgroup":"Not Married, Male, 0-17, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[17],"y":[9.80417739299739],"text":"users: Married, Male, 51-55, A<br />avg_purch_per_order: $9.80<br />users: Married, Male, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(159,166,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 51-55, A","legendgroup":"Married, Male, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[18],"y":[9.7952016037401],"text":"users: Married, Male, 55+, B<br />avg_purch_per_order: $9.80<br />users: Married, Male, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(150,169,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 55+, B","legendgroup":"Married, Male, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[19],"y":[9.7927924561044],"text":"users: Not Married, Male, 46-50, C<br />avg_purch_per_order: $9.79<br />users: Not Married, Male, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(140,171,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 46-50, C","legendgroup":"Not Married, Male, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[20],"y":[9.7803999513267],"text":"users: Not Married, Female, 36-45, C<br />avg_purch_per_order: $9.78<br />users: Not Married, Female, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(129,173,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 36-45, C","legendgroup":"Not Married, Female, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[21],"y":[9.76565518105881],"text":"users: Married, Male, 46-50, B<br />avg_purch_per_order: $9.77<br />users: Married, Male, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(117,175,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 46-50, B","legendgroup":"Married, Male, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[22],"y":[9.64126464030556],"text":"users: Married, Female, 51-55, C<br />avg_purch_per_order: $9.64<br />users: Married, Female, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(104,177,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 51-55, C","legendgroup":"Married, Female, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[23],"y":[9.5924559945657],"text":"users: Married, Male, 55+, C<br />avg_purch_per_order: $9.59<br />users: Married, Male, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(88,179,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 55+, C","legendgroup":"Married, Male, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[24],"y":[9.54650728374946],"text":"users: Not Married, Female, 46-50, C<br />avg_purch_per_order: $9.55<br />users: Not Married, Female, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(68,181,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 46-50, C","legendgroup":"Not Married, Female, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[25],"y":[9.51920159777195],"text":"users: Not Married, Male, 26-35, B<br />avg_purch_per_order: $9.52<br />users: Not Married, Male, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(36,183,0,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 26-35, B","legendgroup":"Not Married, Male, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[26],"y":[9.5114853877641],"text":"users: Married, Male, 18-25, B<br />avg_purch_per_order: $9.51<br />users: Married, Male, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,184,33,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 18-25, B","legendgroup":"Married, Male, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[27],"y":[9.48799576386637],"text":"users: Not Married, Female, 51-55, C<br />avg_purch_per_order: $9.49<br />users: Not Married, Female, 51-55, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 51-55, C","legendgroup":"Not Married, Female, 51-55, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[28],"y":[9.45938784335243],"text":"users: Not Married, Male, 0-17, C<br />avg_purch_per_order: $9.46<br />users: Not Married, Male, 0-17, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,187,73,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 0-17, C","legendgroup":"Not Married, Male, 0-17, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[29],"y":[9.44397924983126],"text":"users: Married, Male, 51-55, B<br />avg_purch_per_order: $9.44<br />users: Married, Male, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,188,88,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 51-55, B","legendgroup":"Married, Male, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[30],"y":[9.3989181296094],"text":"users: Not Married, Male, 18-25, B<br />avg_purch_per_order: $9.40<br />users: Not Married, Male, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,189,100,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 18-25, B","legendgroup":"Not Married, Male, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.899999999999999,"base":0,"x":[31],"y":[9.38241959245651],"text":"users: Married, Female, 36-45, C<br />avg_purch_per_order: $9.38<br />users: Married, Female, 36-45, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,190,112,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 36-45, C","legendgroup":"Married, Female, 36-45, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000002,"base":0,"x":[32],"y":[9.35568400185432],"text":"users: Married, Female, 26-35, C<br />avg_purch_per_order: $9.36<br />users: Married, Female, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,191,123,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 26-35, C","legendgroup":"Married, Female, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[33],"y":[9.32556440146805],"text":"users: Not Married, Male, 36-45, B<br />avg_purch_per_order: $9.33<br />users: Not Married, Male, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,134,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 36-45, B","legendgroup":"Not Married, Male, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[34],"y":[9.31736835745066],"text":"users: Not Married, Male, 46-50, B<br />avg_purch_per_order: $9.32<br />users: Not Married, Male, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,144,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 46-50, B","legendgroup":"Not Married, Male, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[35],"y":[9.30711870389024],"text":"users: Married, Female, 55+, C<br />avg_purch_per_order: $9.31<br />users: Married, Female, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,193,153,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 55+, C","legendgroup":"Married, Female, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[36],"y":[9.3048102251336],"text":"users: Not Married, Female, 46-50, B<br />avg_purch_per_order: $9.30<br />users: Not Married, Female, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,193,162,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 46-50, B","legendgroup":"Not Married, Female, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[37],"y":[9.30465567653891],"text":"users: Not Married, Female, 51-55, B<br />avg_purch_per_order: $9.30<br />users: Not Married, Female, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,193,171,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 51-55, B","legendgroup":"Not Married, Female, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[38],"y":[9.29090003000164],"text":"users: Married, Male, 36-45, B<br />avg_purch_per_order: $9.29<br />users: Married, Male, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,180,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 36-45, B","legendgroup":"Married, Male, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[39],"y":[9.24333881231579],"text":"users: Not Married, Male, 51-55, B<br />avg_purch_per_order: $9.24<br />users: Not Married, Male, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,192,188,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 51-55, B","legendgroup":"Not Married, Male, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[40],"y":[9.16478486254218],"text":"users: Not Married, Female, 18-25, C<br />avg_purch_per_order: $9.16<br />users: Not Married, Female, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,191,196,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 18-25, C","legendgroup":"Not Married, Female, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[41],"y":[9.15786120356485],"text":"users: Married, Male, 26-35, B<br />avg_purch_per_order: $9.16<br />users: Married, Male, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,190,204,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 26-35, B","legendgroup":"Married, Male, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[42],"y":[9.14732935880475],"text":"users: Not Married, Male, 18-25, A<br />avg_purch_per_order: $9.15<br />users: Not Married, Male, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,189,211,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 18-25, A","legendgroup":"Not Married, Male, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[43],"y":[9.10662770854539],"text":"users: Married, Female, 55+, B<br />avg_purch_per_order: $9.11<br />users: Married, Female, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,187,218,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 55+, B","legendgroup":"Married, Female, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[44],"y":[9.08646561405797],"text":"users: Married, Male, 26-35, A<br />avg_purch_per_order: $9.09<br />users: Married, Male, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,186,225,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 26-35, A","legendgroup":"Married, Male, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[45],"y":[9.07735149866713],"text":"users: Not Married, Male, 26-35, A<br />avg_purch_per_order: $9.08<br />users: Not Married, Male, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,183,231,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 26-35, A","legendgroup":"Not Married, Male, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[46],"y":[9.06505600276483],"text":"users: Married, Female, 46-50, C<br />avg_purch_per_order: $9.07<br />users: Married, Female, 46-50, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,181,237,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 46-50, C","legendgroup":"Married, Female, 46-50, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[47],"y":[9.04790783477991],"text":"users: Not Married, Male, 0-17, B<br />avg_purch_per_order: $9.05<br />users: Not Married, Male, 0-17, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,178,243,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 0-17, B","legendgroup":"Not Married, Male, 0-17, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[48],"y":[9.02215641705602],"text":"users: Married, Female, 18-25, C<br />avg_purch_per_order: $9.02<br />users: Married, Female, 18-25, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,175,247,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 18-25, C","legendgroup":"Married, Female, 18-25, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[49],"y":[9.0162655536355],"text":"users: Not Married, Female, 26-35, C<br />avg_purch_per_order: $9.02<br />users: Not Married, Female, 26-35, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,172,252,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 26-35, C","legendgroup":"Not Married, Female, 26-35, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[50],"y":[8.91497481449625],"text":"users: Married, Male, 18-25, A<br />avg_purch_per_order: $8.91<br />users: Married, Male, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,168,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 18-25, A","legendgroup":"Married, Male, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[51],"y":[8.90542257314555],"text":"users: Not Married, Female, 55+, B<br />avg_purch_per_order: $8.91<br />users: Not Married, Female, 55+, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(0,165,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 55+, B","legendgroup":"Not Married, Female, 55+, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[52],"y":[8.8979671368759],"text":"users: Not Married, Female, 55+, C<br />avg_purch_per_order: $8.90<br />users: Not Married, Female, 55+, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(66,160,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 55+, C","legendgroup":"Not Married, Female, 55+, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[53],"y":[8.89683105790223],"text":"users: Not Married, Female, 36-45, B<br />avg_purch_per_order: $8.90<br />users: Not Married, Female, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 36-45, B","legendgroup":"Not Married, Female, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[54],"y":[8.88285347427213],"text":"users: Married, Female, 26-35, A<br />avg_purch_per_order: $8.88<br />users: Married, Female, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(120,151,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 26-35, A","legendgroup":"Married, Female, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[55],"y":[8.87949489438958],"text":"users: Married, Male, 46-50, A<br />avg_purch_per_order: $8.88<br />users: Married, Male, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(139,147,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 46-50, A","legendgroup":"Married, Male, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[56],"y":[8.87154417908347],"text":"users: Married, Male, 36-45, A<br />avg_purch_per_order: $8.87<br />users: Married, Male, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(155,142,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 36-45, A","legendgroup":"Married, Male, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[57],"y":[8.84059326674941],"text":"users: Not Married, Female, 36-45, A<br />avg_purch_per_order: $8.84<br />users: Not Married, Female, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(169,137,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 36-45, A","legendgroup":"Not Married, Female, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[58],"y":[8.82124189822254],"text":"users: Married, Female, 51-55, A<br />avg_purch_per_order: $8.82<br />users: Married, Female, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(182,132,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 51-55, A","legendgroup":"Married, Female, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[59],"y":[8.81259536984174],"text":"users: Married, Female, 26-35, B<br />avg_purch_per_order: $8.81<br />users: Married, Female, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(194,127,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 26-35, B","legendgroup":"Married, Female, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[60],"y":[8.79737418047183],"text":"users: Not Married, Male, 55+, A<br />avg_purch_per_order: $8.80<br />users: Not Married, Male, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(204,122,255,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 55+, A","legendgroup":"Not Married, Male, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[61],"y":[8.76224738339228],"text":"users: Not Married, Female, 0-17, B<br />avg_purch_per_order: $8.76<br />users: Not Married, Female, 0-17, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(213,117,254,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 0-17, B","legendgroup":"Not Married, Female, 0-17, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[62],"y":[8.75567408736133],"text":"users: Married, Female, 36-45, A<br />avg_purch_per_order: $8.76<br />users: Married, Female, 36-45, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(221,113,250,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 36-45, A","legendgroup":"Married, Female, 36-45, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[63],"y":[8.75042898037005],"text":"users: Not Married, Female, 0-17, C<br />avg_purch_per_order: $8.75<br />users: Not Married, Female, 0-17, C","type":"bar","marker":{"autocolorscale":false,"color":"rgba(229,109,245,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 0-17, C","legendgroup":"Not Married, Female, 0-17, C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[64],"y":[8.73738198615461],"text":"users: Married, Male, 55+, A<br />avg_purch_per_order: $8.74<br />users: Married, Male, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(235,105,240,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Male, 55+, A","legendgroup":"Married, Male, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[65],"y":[8.71837491769096],"text":"users: Married, Female, 55+, A<br />avg_purch_per_order: $8.72<br />users: Married, Female, 55+, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(240,102,234,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 55+, A","legendgroup":"Married, Female, 55+, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[66],"y":[8.68887411665767],"text":"users: Not Married, Female, 26-35, A<br />avg_purch_per_order: $8.69<br />users: Not Married, Female, 26-35, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(245,100,227,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 26-35, A","legendgroup":"Not Married, Female, 26-35, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[67],"y":[8.676347097352],"text":"users: Married, Female, 46-50, B<br />avg_purch_per_order: $8.68<br />users: Married, Female, 46-50, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(249,98,221,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 46-50, B","legendgroup":"Married, Female, 46-50, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[68],"y":[8.66130025132357],"text":"users: Married, Female, 36-45, B<br />avg_purch_per_order: $8.66<br />users: Married, Female, 36-45, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(252,97,213,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 36-45, B","legendgroup":"Married, Female, 36-45, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[69],"y":[8.63532404540764],"text":"users: Not Married, Female, 46-50, A<br />avg_purch_per_order: $8.64<br />users: Not Married, Female, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(254,97,206,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 46-50, A","legendgroup":"Not Married, Female, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[70],"y":[8.52929188857589],"text":"users: Not Married, Female, 18-25, A<br />avg_purch_per_order: $8.53<br />users: Not Married, Female, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,97,198,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 18-25, A","legendgroup":"Not Married, Female, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[71],"y":[8.52173628469733],"text":"users: Not Married, Female, 26-35, B<br />avg_purch_per_order: $8.52<br />users: Not Married, Female, 26-35, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,98,189,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 26-35, B","legendgroup":"Not Married, Female, 26-35, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[72],"y":[8.37587437297337],"text":"users: Married, Female, 51-55, B<br />avg_purch_per_order: $8.38<br />users: Married, Female, 51-55, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,99,181,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 51-55, B","legendgroup":"Married, Female, 51-55, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[73],"y":[8.26320545815782],"text":"users: Not Married, Male, 46-50, A<br />avg_purch_per_order: $8.26<br />users: Not Married, Male, 46-50, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,101,172,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Male, 46-50, A","legendgroup":"Not Married, Male, 46-50, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[74],"y":[8.25154741800585],"text":"users: Not Married, Female, 51-55, A<br />avg_purch_per_order: $8.25<br />users: Not Married, Female, 51-55, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,103,162,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 51-55, A","legendgroup":"Not Married, Female, 51-55, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[75],"y":[8.22257697004243],"text":"users: Not Married, Female, 18-25, B<br />avg_purch_per_order: $8.22<br />users: Not Married, Female, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,106,153,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 18-25, B","legendgroup":"Not Married, Female, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[76],"y":[7.62977110331709],"text":"users: Married, Female, 18-25, B<br />avg_purch_per_order: $7.63<br />users: Married, Female, 18-25, B","type":"bar","marker":{"autocolorscale":false,"color":"rgba(255,109,142,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 18-25, B","legendgroup":"Married, Female, 18-25, B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[77],"y":[7.53810266504758],"text":"users: Not Married, Female, 0-17, A<br />avg_purch_per_order: $7.54<br />users: Not Married, Female, 0-17, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(253,112,132,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Not Married, Female, 0-17, A","legendgroup":"Not Married, Female, 0-17, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.900000000000006,"base":0,"x":[78],"y":[7.40106899311184],"text":"users: Married, Female, 18-25, A<br />avg_purch_per_order: $7.40<br />users: Married, Female, 18-25, A","type":"bar","marker":{"autocolorscale":false,"color":"rgba(250,115,121,1)","line":{"width":1.88976377952756,"color":"transparent"}},"name":"Married, Female, 18-25, A","legendgroup":"Married, Female, 18-25, A","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.4494455316373,"r":7.30593607305936,"b":28.1800391389433,"l":37.2602739726027},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":"Наиболее платёжеспособная аудитория (Рис. 20)","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,78.6],"tickmode":"array","ticktext":["Not Married, Male, 51-55, C","Married, Male, 36-45, C","Not Married, Male, 51-55, A","Married, Male, 18-25, C","Married, Male, 26-35, C","Not Married, Male, 26-35, C","Married, Female, 46-50, A","Not Married, Male, 36-45, C","Not Married, Male, 18-25, C","Married, Male, 51-55, C","Not Married, Male, 55+, B","Not Married, Female, 55+, A","Married, Male, 46-50, C","Not Married, Male, 36-45, A","Not Married, Male, 55+, C","Not Married, Male, 0-17, A","Married, Male, 51-55, A","Married, Male, 55+, B","Not Married, Male, 46-50, C","Not Married, Female, 36-45, C","Married, Male, 46-50, B","Married, Female, 51-55, C","Married, Male, 55+, C","Not Married, Female, 46-50, C","Not Married, Male, 26-35, B","Married, Male, 18-25, B","Not Married, Female, 51-55, C","Not Married, Male, 0-17, C","Married, Male, 51-55, B","Not Married, Male, 18-25, B","Married, Female, 36-45, C","Married, Female, 26-35, C","Not Married, Male, 36-45, B","Not Married, Male, 46-50, B","Married, Female, 55+, C","Not Married, Female, 46-50, B","Not Married, Female, 51-55, B","Married, Male, 36-45, B","Not Married, Male, 51-55, B","Not Married, Female, 18-25, C","Married, Male, 26-35, B","Not Married, Male, 18-25, A","Married, Female, 55+, B","Married, Male, 26-35, A","Not Married, Male, 26-35, A","Married, Female, 46-50, C","Not Married, Male, 0-17, B","Married, Female, 18-25, C","Not Married, Female, 26-35, C","Married, Male, 18-25, A","Not Married, Female, 55+, B","Not Married, Female, 55+, C","Not Married, Female, 36-45, B","Married, Female, 26-35, A","Married, Male, 46-50, A","Married, Male, 36-45, A","Not Married, Female, 36-45, A","Married, Female, 51-55, A","Married, Female, 26-35, B","Not Married, Male, 55+, A","Not Married, Female, 0-17, B","Married, Female, 36-45, A","Not Married, Female, 0-17, C","Married, Male, 55+, A","Married, Female, 55+, A","Not Married, Female, 26-35, A","Married, Female, 46-50, B","Married, Female, 36-45, B","Not Married, Female, 46-50, A","Not Married, Female, 18-25, A","Not Married, Female, 26-35, B","Married, Female, 51-55, B","Not Married, Male, 46-50, A","Not Married, Female, 51-55, A","Not Married, Female, 18-25, B","Married, Female, 18-25, B","Not Married, Female, 0-17, A","Married, Female, 18-25, A"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78],"categoryorder":"array","categoryarray":["Not Married, Male, 51-55, C","Married, Male, 36-45, C","Not Married, Male, 51-55, A","Married, Male, 18-25, C","Married, Male, 26-35, C","Not Married, Male, 26-35, C","Married, Female, 46-50, A","Not Married, Male, 36-45, C","Not Married, Male, 18-25, C","Married, Male, 51-55, C","Not Married, Male, 55+, B","Not Married, Female, 55+, A","Married, Male, 46-50, C","Not Married, Male, 36-45, A","Not Married, Male, 55+, C","Not Married, Male, 0-17, A","Married, Male, 51-55, A","Married, Male, 55+, B","Not Married, Male, 46-50, C","Not Married, Female, 36-45, C","Married, Male, 46-50, B","Married, Female, 51-55, C","Married, Male, 55+, C","Not Married, Female, 46-50, C","Not Married, Male, 26-35, B","Married, Male, 18-25, B","Not Married, Female, 51-55, C","Not Married, Male, 0-17, C","Married, Male, 51-55, B","Not Married, Male, 18-25, B","Married, Female, 36-45, C","Married, Female, 26-35, C","Not Married, Male, 36-45, B","Not Married, Male, 46-50, B","Married, Female, 55+, C","Not Married, Female, 46-50, B","Not Married, Female, 51-55, B","Married, Male, 36-45, B","Not Married, Male, 51-55, B","Not Married, Female, 18-25, C","Married, Male, 26-35, B","Not Married, Male, 18-25, A","Married, Female, 55+, B","Married, Male, 26-35, A","Not Married, Male, 26-35, A","Married, Female, 46-50, C","Not Married, Male, 0-17, B","Married, Female, 18-25, C","Not Married, Female, 26-35, C","Married, Male, 18-25, A","Not Married, Female, 55+, B","Not Married, Female, 55+, C","Not Married, Female, 36-45, B","Married, Female, 26-35, A","Married, Male, 46-50, A","Married, Male, 36-45, A","Not Married, Female, 36-45, A","Married, Female, 51-55, A","Married, Female, 26-35, B","Not Married, Male, 55+, A","Not Married, Female, 0-17, B","Married, Female, 36-45, A","Not Married, Female, 0-17, C","Married, Male, 55+, A","Married, Female, 55+, A","Not Married, Female, 26-35, A","Married, Female, 46-50, B","Married, Female, 36-45, B","Not Married, Female, 46-50, A","Not Married, Female, 18-25, A","Not Married, Female, 26-35, B","Married, Female, 51-55, B","Not Married, Male, 46-50, A","Not Married, Female, 51-55, A","Not Married, Female, 18-25, B","Married, Female, 18-25, B","Not Married, Female, 0-17, A","Married, Female, 18-25, A"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":false,"tickfont":{"color":null,"family":null,"size":0},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":"Группа пользователей","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.52469818569428,11.0186618995799],"tickmode":"array","ticktext":["0","1","2","3","4","5","6","7","8","9","10","11"],"tickvals":[0,1,2,3,4,5,6,7,8,9,10,11],"categoryorder":"array","categoryarray":["0","1","2","3","4","5","6","7","8","9","10","11"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":"Сумма покупок","titlefont":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895},"y":1},"hovermode":"closest","width":950,"height":700,"barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"source":"A","attrs":{"181b32ae15d1":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"181b32ae15d1","visdat":{"181b32ae15d1":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><!--/html_preserve-->

Разрыв между категориями людей уже не такой большой, как в количестве покупок. И наиболее привлекательными являются  категории: **Not Married, Female, 0-17, A, Not Married, Female, 0-17, B, Not Married, Female, 0-17, C**. 

Холостые мужчины находятся лишь на 25 месте.

Если бы магазин привлёк больше таких пользователей, то в идеальном случае мог бы получить  **на $40,196,985.94 больше дохода**. Конечно, это не учитывает изменение среднего чека при увеличении аудитории и многих других факторов.

## Выводы

В чёрную пятницу:

1. Холостые люди тратят больше, чем люди в браке.
2. Мужчины покупают больше товаров с более высоким средним чеком.
3. Жители городов класса B тратят больше всего денег.
4. Наименее привлекательные с точки зрения среднего чека -- жители городов группы C.
5. Самые привлекательные пользователи по метрике "доход на пользователя" -- неженатые мужчины 51-55 лет из городов типа C.
6. Самые привлекательные пользователи с точки зрения абсолютного дохода -- неженатые мужчины 26-35 лет из городов типа B.

